import { GodOfWarInterface } from '../../modules/god-of-war/interfaces/god-of-war.interface';

/**
 * Configuración estática que contiene la lista de personajes del módulo God of War.
 *
 * @remarks
 * Esta constante sirve como fuente de datos local para el servicio
 * `GodOfWarCharactersService`, proporcionando información detallada de cada personaje
 * conforme a la estructura definida en `GodOfWarInterface`.
 */
export const GOD_OF_WAR_CHARACTERS: GodOfWarInterface[] = [
  {
    id: 1,
    name: 'Kratos',
    alias: 'Fantasma de Esparta',
    species: 'Dios',
    origin: 'Grecia',
    role: 'Protagonista',
    weapon: 'Hacha Leviatán',
    game: 'God of War Ragnarök',
    powerLevel: 100,
  },
  {
    id: 2,
    name: 'Atreus',
    alias: 'Loki',
    species: 'Semidiós / Gigante',
    origin: 'Midgard / Jötunheim',
    role: 'Protagonista',
    weapon: 'Arco de garra',
    game: 'God of War Ragnarök',
    powerLevel: 75,
  },
  {
    id: 3,
    name: 'Freya',
    alias: 'Bruja del Bosque',
    species: 'Diosa Vanir',
    origin: 'Vanaheim',
    role: 'Aliada',
    weapon: 'Espada y magia',
    game: 'God of War Ragnarök',
    powerLevel: 85,
  },
  {
    id: 4,
    name: 'Thor',
    alias: 'Dios del Trueno',
    species: 'Dios Aesir',
    origin: 'Asgard',
    role: 'Antagonista',
    weapon: 'Mjölnir',
    game: 'God of War Ragnarök',
    powerLevel: 98,
  },
  {
    id: 5,
    name: 'Odin',
    alias: 'Padre de Todo',
    species: 'Dios Aesir',
    origin: 'Asgard',
    role: 'Antagonista',
    weapon: 'Gungnir y magia',
    game: 'God of War Ragnarök',
    powerLevel: 99,
  },
  {
    id: 6,
    name: 'Mimir',
    alias: 'El hombre más inteligente',
    species: 'Ser mitológico',
    origin: 'Midgard',
    role: 'Aliado',
    weapon: 'Conocimiento',
    game: 'God of War Ragnarök',
    powerLevel: 70,
  },
  {
    id: 7,
    name: 'Brok',
    alias: 'El hermano azul',
    species: 'Enano',
    origin: 'Svartalfheim',
    role: 'Aliado',
    weapon: 'Herrería',
    game: 'God of War Ragnarök',
    powerLevel: 65,
  },
  {
    id: 8,
    name: 'Sindri',
    alias: 'El hermano rojo',
    species: 'Enano',
    origin: 'Svartalfheim',
    role: 'Aliado',
    weapon: 'Herrería',
    game: 'God of War Ragnarök',
    powerLevel: 65,
  },
  {
    id: 9,
    name: 'Týr',
    alias: 'Dios de la guerra',
    species: 'Dios Aesir',
    origin: 'Asgard',
    role: 'Aliado',
    weapon: 'Espadas',
    game: 'God of War Ragnarök',
    powerLevel: 90,
  },
  {
    id: 10,
    name: 'Heimdall',
    alias: 'Guardián del Bifröst',
    species: 'Dios Aesir',
    origin: 'Asgard',
    role: 'Antagonista',
    weapon: 'Hofund',
    game: 'God of War Ragnarök',
    powerLevel: 95,
  },
];